export const heroVisualPrompts = {
  hero: "Photorealistic outdoor scene of three teenagers or young adults in a modern UK city park at golden hour, spaced apart and naturally forming a triangle, each holding a phone, moving with energy, casual streetwear, authentic social atmosphere, premium mobile game campaign photography, subtle glowing triangle line overlay connecting the three players, natural daylight, candid not posed, no sci-fi interface, no stock photo feel",
  events:
    "Photorealistic group of young people gathering outdoors for a local mobile game event in an urban public space, people arriving, checking phones, chatting, forming loose groups, modern UK city backdrop, early evening light, premium editorial campaign style, subtle triangle motif, authentic social energy, no fantasy, no corporate staging, no cheesy stock photography",
  social:
    "Photorealistic friends moving together through an outdoor city walkway while playing a mobile game, laughing, jogging, turning towards each other, casual modern fashion, daylight or blue-hour lighting, premium editorial feel, subtle glowing triangle path overlay, real and grounded, not illustrative, not exaggerated",
  teams:
    "Photorealistic outdoor company group activity in a modern office campus or park setting, mixed team of adults in casual-smart clothing using phones and moving in small groups, upbeat and social, premium event photography, natural expressions, daylight, subtle triangle overlay suggesting gameplay, no handshake clichés, no lanyard-heavy conference feel",
};

export const quickStartItems = [
  {
    icon: "01",
    title: "Join what’s happening",
    description: "Pick an event with real momentum and jump into a match that’s already coming together.",
  },
  {
    icon: "02",
    title: "Spread out fast",
    description: "Once the match starts, teams move, space opens up, and the triangle starts to matter.",
  },
  {
    icon: "03",
    title: "Play it properly",
    description: "Read the space, move together, and turn a simple setup into a sharp outdoor game.",
  },
];

export const eventScopeFilters = [
  { key: "local", label: "Local events" },
  { key: "city", label: "City events" },
  { key: "global", label: "Global events" },
  { key: "away_day", label: "Away-day events" },
];

export const eventTimeFilters = [
  { key: "today", label: "Today" },
  { key: "week", label: "This week" },
  { key: "month", label: "This month" },
];

export const events = [
  {
    name: "After School Rush",
    location: "Victoria Park, London",
    time: "Today · 5:30 pm",
    liveLabel: "Starting soon",
    players: 14,
    status: "Starting soon",
    statusKey: "starting",
    typeLabel: "Session",
    distance: "480m away",
    playersActive: 0,
    teamsForming: 4,
    ctaLabel: "Mark ready",
    scope: "local",
    timeframe: "today",
    featured: true,
    sceneClass: "park",
    intro: "Fast turnout, open ground, and loads of room to make big plays before dark.",
    microcopy: "Four teams forming. Good space, quick starts, and plenty of room to stretch the triangle.",
  },
  {
    name: "Park Openers",
    location: "Clissold Park, London",
    time: "Today · 6:00 pm",
    liveLabel: "Players joining",
    players: 11,
    status: "Players joining",
    statusKey: "joining",
    typeLabel: "Session",
    distance: "1.2km away",
    playersActive: 0,
    teamsForming: 3,
    ctaLabel: "Join session",
    scope: "local",
    timeframe: "today",
    featured: false,
    sceneClass: "park",
    intro: "Big lawns, clean sightlines, and a quick early-evening session that gets moving fast.",
    microcopy: "Three teams forming. Easy to read, easy to join, and always lively once the first triangle lands.",
  },
  {
    name: "Saturday City Run",
    location: "South Bank, London",
    time: "Sat · 2:00 pm",
    liveLabel: "Busy",
    players: 22,
    status: "Busy",
    statusKey: "busy",
    typeLabel: "Flagship",
    distance: "2.1km away",
    playersActive: 0,
    teamsForming: 7,
    ctaLabel: "Register team",
    scope: "city",
    timeframe: "week",
    featured: false,
    sceneClass: "river",
    intro: "A bigger crowd, a longer route, and more teams to read, track, and outplay.",
    microcopy: "A bigger weekly session with more teams, longer routes, and city-level bragging rights.",
  },
  {
    name: "Lunch Break Triangle",
    location: "Canary Wharf",
    time: "Tomorrow · 12:30 pm",
    liveLabel: "Filling up",
    players: 8,
    status: "Filling up",
    statusKey: "filling",
    typeLabel: "Quick play",
    distance: "620m away",
    playersActive: 0,
    teamsForming: 2,
    ctaLabel: "RSVP",
    scope: "city",
    timeframe: "week",
    featured: false,
    sceneClass: "city",
    intro: "A tight lunchtime match with quick decisions, sharp turns, and no time to hesitate.",
    microcopy: "Quick lunchtime hit. Short warm-up, sharp turns, and two teams already pulling together.",
  },
  {
    name: "Golden Hour Match",
    location: "Battersea Park",
    time: "Fri · 5:45 pm",
    liveLabel: "Filling up",
    players: 16,
    status: "Filling up",
    statusKey: "filling",
    typeLabel: "Framed session",
    distance: "3.3km away",
    playersActive: 0,
    teamsForming: 5,
    ctaLabel: "Save your spot",
    scope: "local",
    timeframe: "week",
    featured: false,
    sceneClass: "plaza",
    intro: "A brighter Friday session with long lanes, quick pivots, and enough teams to keep the pressure on.",
    microcopy: "Five teams lining up. Best for fast feet, quick calls, and a bit of end-of-week chaos.",
  },
  {
    name: "Campus Cutback",
    location: "King’s Cross Square",
    time: "Thu · 6:15 pm",
    liveLabel: "Players joining",
    players: 9,
    status: "Players joining",
    statusKey: "joining",
    typeLabel: "Quick play",
    distance: "1.7km away",
    playersActive: 0,
    teamsForming: 3,
    ctaLabel: "RSVP",
    scope: "city",
    timeframe: "week",
    featured: false,
    sceneClass: "campus",
    intro: "Short routes, tight corners, and a session built for quick triangles and sharp recoveries.",
    microcopy: "Three teams pulling together near the square. Feels quick, tactical, and properly social.",
  },
  {
    name: "River Run Warm-Up",
    location: "Hackney Wick",
    time: "Thu · 7:00 pm",
    liveLabel: "Starting soon",
    players: 12,
    status: "Starting soon",
    statusKey: "starting",
    typeLabel: "Session",
    distance: "2.8km away",
    playersActive: 0,
    teamsForming: 4,
    ctaLabel: "Mark ready",
    scope: "city",
    timeframe: "week",
    featured: false,
    sceneClass: "river",
    intro: "Waterside routes, longer pulls, and just enough open space to punish teams that overcommit.",
    microcopy: "Four teams forming. Good for longer runs, bigger shapes, and cleaner calls.",
  },
  {
    name: "Last Light Session",
    location: "Alexandra Palace",
    time: "Sun · 4:00 pm",
    liveLabel: "Busy",
    players: 19,
    status: "Busy",
    statusKey: "busy",
    typeLabel: "Flagship",
    distance: "5.2km away",
    playersActive: 0,
    teamsForming: 6,
    ctaLabel: "Register team",
    scope: "away_day",
    timeframe: "month",
    featured: false,
    sceneClass: "plaza",
    intro: "Long views, late light, and enough open ground to make the trip worth it.",
    microcopy: "A bigger away-day session with room for long lanes, resets, and late-match swings.",
  },
  {
    name: "Canal Side Clash",
    location: "Granary Square",
    time: "Tomorrow · 6:45 pm",
    liveLabel: "Players joining",
    players: 13,
    status: "Players joining",
    statusKey: "joining",
    typeLabel: "Framed session",
    distance: "1.9km away",
    playersActive: 0,
    teamsForming: 4,
    ctaLabel: "Join session",
    scope: "city",
    timeframe: "week",
    featured: false,
    sceneClass: "city",
    intro: "Strong foot traffic, shifting lanes, and the sort of central match that turns tactical very quickly.",
    microcopy: "Four teams forming by the square. Best when you can stretch the space without losing the line.",
  },
  {
    name: "Paris River Sprint",
    location: "Seine Left Bank, Paris",
    time: "This month · Sat · 3:00 pm",
    liveLabel: "Planned",
    players: 24,
    status: "Teams opening",
    statusKey: "filling",
    typeLabel: "Global",
    distance: "Eurostar weekend",
    playersActive: 0,
    teamsForming: 8,
    ctaLabel: "Track trip",
    scope: "global",
    timeframe: "month",
    featured: false,
    sceneClass: "river",
    intro: "One of the bigger shared-city formats, built around long routes, landmarks, and proper travel energy.",
    microcopy: "Cross-city fixture with travelling players, bigger teams, and a proper destination feel.",
  },
  {
    name: "Berlin Night Grid",
    location: "Tempelhof Field, Berlin",
    time: "This week · Fri · 7:15 pm",
    liveLabel: "Forming",
    players: 18,
    status: "Players joining",
    statusKey: "joining",
    typeLabel: "Global",
    distance: "Short-haul trip",
    playersActive: 0,
    teamsForming: 6,
    ctaLabel: "Follow event",
    scope: "global",
    timeframe: "week",
    featured: false,
    sceneClass: "plaza",
    intro: "Big open space, later light, and the kind of session people plan travel around.",
    microcopy: "A global-city fixture with open lanes, strong turnout, and plenty of room to read the field.",
  },
  {
    name: "Brighton Seafront Away Day",
    location: "Brighton Seafront",
    time: "This month · Sun · 1:00 pm",
    liveLabel: "Coach list open",
    players: 20,
    status: "Travel group building",
    statusKey: "starting",
    typeLabel: "Away day",
    distance: "Day trip",
    playersActive: 0,
    teamsForming: 6,
    ctaLabel: "Save a seat",
    scope: "away_day",
    timeframe: "month",
    featured: false,
    sceneClass: "river",
    intro: "A destination session built around the travel, the social side, and one long outdoor match.",
    microcopy: "Day-trip format with travel planning, team groups, and plenty of open seafront space.",
  },
];

export const eventSchedule = [
  {
    day: "Monday",
    time: "6:00 pm",
    name: "Park Openers",
    sceneClass: "park",
    blurb: "Straight into it after school or work. Wide space, easy turnout, quick first rounds.",
  },
  {
    day: "Tuesday",
    time: "5:30 pm",
    name: "After School Rush",
    sceneClass: "park",
    blurb: "The weekly one that gets loud quickly. Strong turnout, open grass, and fast decisions.",
  },
  {
    day: "Wednesday",
    time: "12:30 pm",
    name: "Lunch Break Triangle",
    sceneClass: "city",
    blurb: "Short, sharp, and tight on time. Good for quick legs and cleaner calls.",
  },
  {
    day: "Thursday",
    time: "6:15 pm",
    name: "Campus Cutback",
    sceneClass: "campus",
    blurb: "Tighter lanes and quicker recoveries around the square.",
  },
  {
    day: "Friday",
    time: "5:45 pm",
    name: "Golden Hour Match",
    sceneClass: "plaza",
    blurb: "Big Friday energy, longer shapes, and loads of end-of-week momentum.",
  },
  {
    day: "Saturday",
    time: "2:00 pm",
    name: "Saturday City Run",
    sceneClass: "river",
    blurb: "The bigger weekly fixture with more teams, more space, and more bragging rights.",
  },
  {
    day: "Sunday",
    time: "4:00 pm",
    name: "Last Light Session",
    sceneClass: "plaza",
    blurb: "Late-week outdoor play with room to bait, trap, and turn matches around.",
  },
];

export const weeklyFeature = {
  label: "Featured weekly format",
  name: "After School Rush",
  time: "Tuesdays · 5:30 pm",
  sceneClass: "park",
  description:
    "Quick turnout, open space, and a fast match that gets loud almost immediately.",
};

export const audienceCards = [
  {
    title: "Play with friends",
    description:
      "Turn a normal meet-up into an outdoor game with movement, teamwork, and the kind of chaos that makes people want another round.",
    ctaLabel: "Play with friends",
    href: "#final-cta",
    sceneClass: "friends",
  },
  {
    title: "Team events",
    description:
      "Great for away days and socials that need movement, teamwork, and a simple format people get quickly.",
    ctaLabel: "Plan a team event",
    href: "./contact.html",
    sceneClass: "teams",
  },
];

export const steps = [
  {
    number: "1",
    title: "Join a game",
    description: "Pick an event or start one from the app.",
  },
  {
    number: "2",
    title: "Spread out",
    description: "Three players form one triangle in real space.",
  },
  {
    number: "3",
    title: "Beat smaller teams",
    description: "Bigger, smarter triangles beat smaller ones.",
  },
];

export const leaderboardScopes = [
  { key: "games", label: "Events" },
  { key: "local", label: "Local" },
  { key: "city", label: "City" },
  { key: "global", label: "Global" },
];

export const leaderboardTimes = [
  { key: "daily", label: "Today" },
  { key: "weekly", label: "This week" },
  { key: "all_time", label: "All time" },
];

export const socialChannels = [
  {
    platform: "Instagram",
    handle: "@triangulate.live",
    href: "https://www.instagram.com/triangulate.live/",
    label: "Reels, Stories, event drops",
    description: "Follow the visual side of Triangulate: event alerts, short explainers, and recaps from the map.",
  },
  {
    platform: "TikTok",
    handle: "@triangulate.live",
    href: "https://www.tiktok.com/@triangulate.live",
    label: "Short clips, tactics, launch energy",
    description: "Quick videos that show how three points turn a normal place into a real-world strategy game.",
  },
];

// Approved public posts can be added here once the social accounts publish.
// Keep this list to brand-owned posts only, and do not include player names or
// identifiable user content unless consent is documented.
// Shape:
// { platform: "Instagram", title: "...", description: "...", href: "https://...", publishedAt: "2026-04-23", label: "Reel" }
export const socialPosts = [];
